### ISSUE TITLE
Abandon SMV Scala project interface

### ISSUE THREAD

**Issue by ninjapapa** [TresAmigosSD/SMV#1338]
All of our client projects were used the Python interface, and all of our internal Scala projects were converted to Python projects too, so we are ready to finally take the move to remove Scala project support.

This is and umbrella issue, and some of the child issues could also be umbrella by themselves.

* [x] Remove utility scripts for Scala project lauching #1375
* [x] Remove Scala interface from docs #1346
* [x] Move `SmvDesc` and `SmvLabel` implementation to Python #1341
* [x] Remove Scala `SmvDataSet` interface classes #1339 
* [x] Remove `DataSetRepoScala` #1351
* [x] Move `createGraphJSON` and all graph tools to Python #1378 
* [x] Move all `SmvApp` functions from Scala to Python
* [x] Move SmvConfig to Python #1384
* [x] Move `DataSetMgr` to Python #1390

The following depends on other refactors works, on-hold for now 
* [x] Simplify Scala `SmvDataSet` framework classes to just support python `SmvDataSet` #1347
* [x] Create Python side `DataSetRepo` #1417 
* [ ] Remove `DataSetRepo` framework and Scala `SmvDataSet` base class #1421

**Comment by ninjapapa** [comment]
Only one child left. Close this one.

**Comment by ninjapapa** [comment]
Only one child left. Close this one.
