### ISSUE TITLE
☔️ Use SemaphoreCI to build/test SMV

### ISSUE THREAD

**Issue by AliTajeldin** [TresAmigosSD/SMV#1575]
* [x] add steps to Makefile and/or scripts to setup environment on CI
* [x] add steps to Makefile and/or scripts to build on CI
* [x] add steps to Makefile to run tests on CI.
* [x] create script to upload/download latest SMV release built on CI #1572

**Comment by AliTajeldin** [comment]
All above was done in a single PR, closing
